# Generated by Django 2.0.2 on 2018-06-02 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0003_auto_20180601_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 2, 15, 53, 57, 509157, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 2, 15, 53, 57, 508562, tzinfo=utc)),
        ),
    ]
