# Generated by Django 2.0.2 on 2018-06-02 15:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0005_auto_20180602_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 2, 15, 54, 37, 227786, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 2, 15, 54, 37, 227092, tzinfo=utc)),
        ),
    ]
